---
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=information-setting-up-installation-environment-variables
apiVersion: batch/v1
kind: Job
metadata:
  name: validate-parameters
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: val-par-cpdenv01
          image: "icr.io/cpopen/cpd/olm-utils-v2:4.8.2"
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: cp4denv01
          env:        
            - name: CPD_CLI_MANAGE_WORKSPACE
              value: /tmp
          command:
            - /bin/bash
            - -c
            - |
              set -eo pipefail
              set -x
              echo "Paremeters used are ${VERSION} and ${COMPONENTS}"
              echo "With namespaces : ${PROJECT_CPD_INST_OPERATORS} and ${PROJECT_CPD_INST_OPERANDS}"
              result=0
              exit ${result}
            
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
  backoffLimit: 1