# The following enables the operators in the wim-oper project to manage objects, such as custom resources, in the wim-oper project.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "085"
  name: nss-managed-role-from-wim-oper
  namespace: wim-oper
  labels:
    managed-by: nss
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection    
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-wim-oper
  namespace: wim-oper
  labels:
    managed-by: nss
subjects:
- kind: ServiceAccount
  name: ibm-namespace-scope-operator
  namespace: wim-oper
roleRef:
  kind: Role
  name: nss-managed-role-from-wim-oper
  apiGroup: rbac.authorization.k8s.io


# Create namespace wim-inst
oc create namespaces wim-inst

# The following commands enable the operators in the wim-oper project to manage objects, such as custom resources, in the wim-inst project.
cat <<EOF | oc apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nss-managed-role-from-wim-oper
  namespace: wim-inst
  labels:
    managed-by: nss
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection    
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nss-managed-role-from-wim-oper
  namespace: wim-inst
  labels:
    managed-by: nss
subjects:
- kind: ServiceAccount
  name: ibm-namespace-scope-operator
  namespace: wim-oper
roleRef:
  kind: Role
  name: nss-managed-role-from-wim-oper
  apiGroup: rbac.authorization.k8s.io