---
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=installing
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "215"
  name: cp4d-install-cognosanalytics
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: install-cognosanalytics
          image: "icr.io/cpopen/cpd/olm-utils-v2:latest"
          envFrom:
          - configMapRef:
              name: crrs
          command:
            - /bin/bash
            - -c
            - |
              set -eo pipefail
              set -x

              result=0

              export KUBECONFIG=/tmp/kubeconfig
              api_url=$(oc get Infrastructure cluster -o jsonpath='{.status.apiServerURL}')
              oc login "${api_url}" --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --insecure-skip-tls-verify \
              || {
                  echo "WARNING: Unable to login to the cluster."
                  exit 1
              }

              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services
              echo "INFO: Installing cognos_analytics" \
              && bin/authorize-instance-topology \
                  --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS:?} \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS:?} \
              && bin/setup-instance-topology \
                  --release=${VERSION:?} \
                  --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS:?} \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS:?} \
                  --license_acceptance=true \
                  --block_storage_class=${STG_CLASS_BLOCK} \
              && bin/get-license \
                  --release=${VERSION} \
                  --license-type=EE \
              && echo "INFO: Creating OLM objects for a specialized installation." \
              && bin/apply-olm apply-olm \
                  --release=${VERSION} \
                  --components=cognos_analytics \
                  --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS} \
              || result=1


              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak
              echo "INFO: Installing components in a specialized installation." \
              && bin/apply-cr \
                  --components=cognos_analytics\
                  --release=${VERSION} \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS:?} \
                  --block_storage_class=${STG_CLASS_BLOCK:?} \
                  --file_storage_class=${STG_CLASS_FILE:?} \
                  --license_acceptance=true \
              && bin/get-cr-status \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS} \
              && echo "INFO: CP4D platform installation complete." \
              || {
                  echo "ERROR: CP4D cognos_analytics failed."
                  result=1
              }

              exit ${result}

      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller

  backoffLimit: 2
