---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp-shared-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/project
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  source:
    helm:
      parameters:
        - name: argocd_app_name
          value: cp-shared-app
        - name: argocd_app_namespace
          value: ibm-cloudpaks
        - name: dedicated_cs.control_namespace
          value: cs-control
        - name: dedicated_cs.enabled
          value: false
        - name: dedicated_cs.namespace_mapping.cp4i
          value: cp4i
        - name: dedicated_cs.namespace_mapping.cp4s
          value: cp4s
        - name: metadata.ibm_cert_manager_channel
          value: "v4.2"
        - name: metadata.ibm_cert_manager_namespace
          value: "ibm-cert-manager"
        - name: metadata.ibm_cert_manager_operator_group
          value: "ibm-cert-manager-operator-group"
        - name: online_catalog_source_priority
          value: "-1"
        - name: repoURL
          value: "https://github.com/CPDWim/euNTT/"
        - name: serviceaccount.argocd_application_controller
          value: "openshift-gitops-argocd-application-controller"
    path:  config/cloudpaks/cp-shared/
    repoURL:  "https://github.com/CPDWim/euNTT/"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
