kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deconstruct-pvc
  namespace: openshift-gitops
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 100Gi 
  storageClassName: ocs-storagecluster-cephfs

