kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deconstruct-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 100Gi 
  storageClassName: ocs-storagecluster-cephfs

