---
# Source: databand/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: databand-postgresql
  namespace: "databand-system"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.6.2
    app.kubernetes.io/instance: databand
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: databand
    app.kubernetes.io/component: primary
