---
# Source: databand/templates/deployment-celery-beat.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: databand-celery-beat
  labels:
    app: databand
    component: celery-beat
    baseComponent: databand-webserver
    chart: databand-1.0.59-4
    release: databand
    heritage: Helm
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    # Smooth rolling update of the celery-beat service
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: databand
      component: celery-beat
      release: databand
  template:
    metadata:
      annotations:
        checksum/config-env: 3109c2a9a50dcf23eb23cd5b7154adb3449d16cbcda947dbcbe23ae8556ea817
      labels:
        app: databand
        component: celery-beat
        baseComponent: databand-webserver
        release: databand
    spec:
      imagePullSecrets:
        - name: regcred.gitlab.databand
      restartPolicy: Always
      containers:
        - name: databand-celery-beat
          image: image-registry.openshift-image-registry.svc:5000/databand/dbnd-webserver:python-v1.0.59.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: "databand-env"
          env:          
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          volumeMounts:
            - name: dbnd-celerybeat-schedule
              mountPath: /dbnd/beat
            - name: dbnd-prom
              mountPath: /dbnd/prom
          args:
            - "bash"
            - "-c"
            - echo 'wait for DB to pass validation...' && dbnd-web db --wait validate --wait-until-pass --timeout-until-pass 3600 && echo "executing  dbnd-web celery beat -s beat/celerybeat-schedule..." && dbnd-web celery beat -s beat/celerybeat-schedule
      volumes:
        - name: dbnd-celerybeat-schedule
          emptyDir: {}
        - name: dbnd-prom
          emptyDir: {}
