---
# Source: databand/templates/service-rule-engine.yaml
apiVersion: v1
kind: Service
metadata:
  name: databand-rule-engine
  labels:
    app: databand
    component: rule-engine
    chart: databand-1.0.59-4
    release: databand
    heritage: Helm

spec:
  type: ClusterIP
  selector:
    app: databand
    component: rule-engine
    release: databand
  ports:
    - name: rule-engine
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: rule-engine-app
      protocol: TCP
      port: 5000
      targetPort: 5000
