---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4denv02
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/project
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  source:
    helm:
      parameters:
        - name: app-name
          value: cp4denv02
        - name: components
          value: cpd_platform,wkc
        - name: operators_namespace
          value: cp4denv02-oper
        - name: operands_namespace
          value: cp4denv02-inst
    path: config/cloudpaks/cp4denvs
    repoURL:  "https://github.com/CPDWim/euNTT/"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
