---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4denv02
spec:
  destination:
    namespace: cp4d-02
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/project
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  source:
    path: ../../cloudpaks/cp4denvs
    repoURL:  "https://github.com/CPDWim/euNTT/"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
