---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0000-config-placeholder.yaml
  - 0000-validate-parameters.yaml
  - ../../base
  #- 0000-cpd-namespaces.yaml
patches:
  # - path: env-config-placeholder.yaml
  #- path: env-postsync-certificates.yaml
  - path: env-sync-cluster-setup.yaml
  - path: env-sync-install-olm.yaml
  - path: env-sync-install-platform.yaml
  - path: env-sync-install-zen-workaround.yaml