---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4denv01
  namespace: {{.Values.metadata.argocd_namespace}}
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  path: config/cloudpaks/cp4denv01
  repoURL:  "https://github.com/CPDWim/euNTT/"
  targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
