---
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=installing
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "102"
  name: sync-cp4d-install-components
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - name: install-components
          command:
            - /bin/bash
            - -c
            - |
              set -eo pipefail
              set -x

              result=0

              export KUBECONFIG=/tmp/kubeconfig
              api_url=$(oc get Infrastructure cluster -o jsonpath='{.status.apiServerURL}')
              oc login "${api_url}" --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --insecure-skip-tls-verify \
              || {
                  echo "WARNING: Unable to login to the cluster."
                  exit 1
              }

              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=requirements-hardware#hardware-reqs__svc-power
              linux_arch=$(uname -p)
              if [ "${linux_arch}" == "ppc64le" ] || [ "${linux_arch}" == "s390x" ]; then
                  COMPONENTS=${COMPONENTS/,rstudio/}
              fi

              # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak
              echo "INFO: Installing components in a specialized installation." \
              && bin/apply-cr \
                  --components=${COMPONENTS:?} \
                  --release=${VERSION} \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS:?} \
                  --block_storage_class=${STG_CLASS_BLOCK:?} \
                  --file_storage_class=${STG_CLASS_FILE:?} \
                  --license_acceptance=true \
              && bin/get-cr-status \
                  --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS} \
              && echo "INFO: CP4D installation complete." \
              || {
                  echo "ERROR: CP4D installation failed."
                  result=1
              }

              exit ${result}

      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller

  backoffLimit: 2
